B1=input("Masukan bilangan 1:")
B2=input("Masukan bilangan 2:")
B3=input("Masukan bilangan 3:")
if B1>=B2>=B3 : print("Bilangan terbesar adalah ", B1)
elif B1>=B3>=B2 : print("Bilangan terbesar adalah ", B1)
elif B2>=B1>=B3 : print("Bilangan terbesar adalah ", B2)
elif B2>=B3>=B1 : print("Bilangan terbesar adalah ", B2)
elif B3>=B1>=B2 : print("Bilangan terbesar adalah ", B3)
else : print("Bilangan terbesar adalah ", B3)
if B1>=B2>=B3 : print("Bilangan terkecil adalah ", B3)
elif B1>=B3>=B2 : print("Bilangan terkecil adalah ", B2)
elif B2>=B1>=B3 : print("Bilangan terkecil adalah ", B3)
elif B2>=B3>=B1 : print("Bilangan terkecil adalah ", B1)
elif B3>=B1>=B2 : print("Bilangan terkecil adalah ", B2)
else : print("Bilangan terkecil adalah ", B1)

